# Timelog

* Machine Learning Models to Detect Arrhythmia based on ECG Data - Interpretability
* Shourya Verma
* 2308432v
* Dr. Fani Deligianni

## Guidance

* This file contains the time log for your project. It will be submitted along with your final dissertation.
* **YOU MUST KEEP THIS UP TO DATE AND UNDER VERSION CONTROL.**
* This timelog should be filled out honestly, regularly (daily) and accurately. It is for *your* benefit.
* Follow the structure provided, grouping time by weeks.  Quantise time to the half hour.

## Week 1

### 30 Sept 2020

* *2 hours* Read the project guidance notes
* *4 hours* Read the reserch papers for the project
* *0.5 hour* Created GitLab repository

## Week 2

### 5 Oct 2020

* *1 hour* meeting with supervisor
* *2 hours* Downloaded the dataset and created jupyter notebook

### 8 Oct 2020

* *1 hour* Read the research papers
* *2 hours* Initial code using wfdb library

### 10 Oct 2020

* *1 hour* Read the research papers
* *2 hours* made plots for the ecg data
* *1 hours* made the google slides

### 11 Oct 2020

* *1 hour* Visualizing ECG data 
* *2 hours* Segmenting  of ECG data
* *1 hours* Annoation distribution graph

### 12 Oct 2020

* *1 hour* Meetig with Supervisor
* *2 hours* Segmentation of annotated classes
* *1 hours* Read research paper

## Week 3

### 13 Oct 2020

* *1 hour* Extracting heartbeat from data
* *2 hours* creating ecg dataset from heartbeats


### 15 Oct 2020

* *1 hour* Normalization and Standardization of data
* *2 hours* remove unclasssified beats


### 17 Oct 2020

* *2 hours* Resampling the frequency
* *1 hours* Saving all beats into csv file

### 18 Oct 2020

* *1 hour* Created google slides
* *2 hours* fixed bugs

### 19 Oct 2020

* *1 hour* Meeting with supervisor

## Week 4

### 21 Oct 2020

* *1 hour* UMAP and PCA analysis
* *2 hours* TSNE and LOOCV

### 22 Oct 2020

* *1 hour* GPU problems
* *2 hours* solving GPU issues

### 23 Oct 2020

* *1 hour* Reaserch on Data Visualization
* *3 hours* Docker and GPU cluster

### 25 Oct 2020

* *1 hour* making yaml and files ready for GPU cluster
* *2 hours* more GPU issues
* *2 hour* UMAPS for cluster identification
* *3 hours* Slides and more visualization 

## Week 5

### 26 Oct 2020

* *1 hour* PCA with and without TSNE different n components
* *2 hours* all scores for 75-25, 70-30 from GPU clusters

### 28 Oct 2020

* *1 hour* cluster pending and unscheduled
* *2 hours* GPU cluster problems

### 1 Nov 2020

* *1 hour* Read the research papers
* *2 hours* make presentation

### 2 Nov 2020

* *1 hour* Meeting with supervisor
* *2 hours* Research papers for CNN
* *1 hours* Confusion matrices and pytorch

## Week 6

### 4 Nov 2020

* *1 hour* Read more papers on CNN
* *2 hours* Learned about CNN models and architecture
* *1 hours* CNN imported with keras and tensorflow

### 6 Nov 2020

* *1 hour* Tried colab for LOOCV
* *2 hours* Bad LOOCV results so ran it on smaller data
* *1 hours* more LOOCV on colab

### 8 Nov 2020

* *1 hour* Confusion matrices made and compared
* *2 hours* CNN model research and prepared


### 9 Nov 2020

* *1 hour* CNN model ran and prepared scores and confusion matrix
* *2 hours* tried to visualize CNN
 
## Week 7

### 10 Nov 2020

* *2 hours* Saliency maps research
* *1 hours* Interpretability research

### 12 Nov 2020

* *1 hour* Tried Keras vis
* *2 hours* fixing keras vis incompatibility to TF2

### 14 Nov 2020

* *1 hour* Asking Yola for help 

### 16 Nov 2020

* *1 hour* Supervisor meeting
* *2 hours* Patient index for each record

### 27 Oct 2020

* *1 hour* TSNE and UMAP visualization
* *2 hours* Data dimensionality reduction

### 29 Oct 2020

* *1 hour* Data split into training and testing
* *3 hours* trained data on different classifiers

### 31 Oct 2020

* *2 hour* More PCA visualization 
* *3 hours* LOOCV implementation

## Week 8

### 2 Nov 2020

* *1 hour* Supervisor meeting
* *2 hours* Research on CNN

### 5 Nov 2020

* *1 hour* Using Yola's advice and changing library code
* *2 hours* reshaping data trying to get it to work

## Week 9

### 18 Nov 2020

* *1 hour* Fixing test train split and resampling
* *2 hours* Performing all classifications again for new method

### 20 Nov 2020

* *1 hour* Read more papers on interpretability
* *2 hours* Tried more LIME methods
* *1 hours* Tried Lime for time

### 21 Nov 2020

* *1 hour* Lime for Time worked but I dont understand it
* *2 hours* Lime for Time very inconsistent for same values
* *1 hours* More Keras vis and Lime for time

### 23 Nov 2020

* *1 hour* Confusion matrices for new methods both sampled and unsampled
* *2 hours* Keras vis is impossoble and deprecated cant fix it
 
## Week 10

### 25 Nov 2020

* *1 hour* Read more papers
* *2 hours* trying to find saliency library

### 27 Nov 2020

* *1 hour* found partial dependence plots paper
* *2 hours* implementing partial dependence plot

## Week 11

### 2 Dec 2020

* *1 hour* found kernel shap paper
* *2 hours* implementing kernel shap

### 5 Dec 2020

* *1 hour* kernel shap only works with SVM
* *3 hours* improving kernel shap explanation

## Week 12

### 11 Jan 2021

* *1 hour* found kernel shap paper
* *2 hours* implementing kernel shap

### 15 Jan 2021

* *1 hour* kernel shap only works with SVM
* *2 hours* improving kernel shap explanation

## Week 13

### 19 Jan 2021

* *1 hour* found kernel shap paper
* *3 hours* implementing kernel shap

### 21 Jan 2021

* *1 hour* improved TSNE UMAP
* *3 hours* improved clusters

## Week 14

### 25 Jan 2021

* *1 hour* found permutation feature importance paper
* *3 hours* implementing permutation feature importance

### 27 Jan 2021

* *1 hour* improved TSNE UMAP
* *2 hours* improved clusters

## Week 15

### 2 Feb 2021

* *1 hour* Kendall Tau correlation of CNN and TSNE
* *2 hours* more feature importance 

### 4 Feb 2021

* *1 hour* found grad-CAM paper
* *3 hours* implementing grad-CAM on CNN and LSTM

## Week 16

### 9 Feb 2021

* *1 hour* implementing grad-cam per class
* *2 hours* trying to see if what i did was right or wrong

### 11 Feb 2021

* *1 hour* average layer weights for CNN and LSTM
* *2 hours* plotting layer weights on ECG beats 

## Week 17

### 16 Feb 2021

* *1 hour* grad-CAM on misclassified beats 
* *3 hours* more misclassified grad-cam

### 20 Feb 2021

* *1 hour* misclassified feeature importance 
* *3 hours* plotting misclassified feature importance

## Week 18

### 23 Feb 2021

* *1 hour* reading about statistical test
* *3 hours* implementing statistical tests

### 26 Feb 2021

* *1 hour* noisy dataset for grad-CAM
* *2 hours* applying noisy dataset for both CNN and LSTM

## Week 19

### 2 Mar 2021

* *1 hour* grad-CAM on misclassified beats 
* *2 hours* more misclassified grad-cam

### 4 Mar 2021

* *1 hour* misclassified feeature importance 
* *3 hours* plotting misclassified feature importance

## Week 20

### 9 Mar 2021

* *1 hour* Kendall tau on segments 
* *3 hours* more stats tests

### 13 Mar 2021

* *1 hour* wilcoxon pairwise tests
* *3 hours* making code dynamic

## Week 21

### 17 Mar 2021

* *1 hour* finishing dynamic code
* *2 hours* finishing evalaution

### 20 Mar 2021

* *1 hour* dissertation
* *2 hours* dissertation

## Week 22

### 23 Mar 2021

* *4 hours* dissertation
* *4 hours* dissertation
### 26 Mar 2021

* *4 hours* dissertation
* *4 hours* dissertation

## Week 23

### 30 Mar 2021

* *4 hours* dissertation
* *4 hours* dissertation

### 2 April 2021

* *4 hours* dissertation
* *4 hours* dissertation